-- Create sequence.
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME));
SELECT * FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN';
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);

-- Remove table, if exists.
DROP TABLE IF EXISTS COLOR;

-- Create table color.
CREATE TABLE color (ID BIGINT NOT NULL AUTO_INCREMENT, DESCRIPTION VARCHAR, PRIMARY KEY (ID));

-- Dump data color.
INSERT INTO COLOR(DESCRIPTION) VALUES('Blue');
INSERT INTO COLOR(DESCRIPTION) VALUES('Red');
INSERT INTO COLOR(DESCRIPTION) VALUES('Green');
INSERT INTO COLOR(DESCRIPTION) VALUES('Grey');
INSERT INTO COLOR(DESCRIPTION) VALUES('Black');
INSERT INTO COLOR(DESCRIPTION) VALUES('Pink');
INSERT INTO COLOR(DESCRIPTION) VALUES('Purple');

-- Remove table, if exists.
DROP TABLE IF EXISTS VEHICLE;

-- Create table vehicle.
CREATE TABLE vehicle (ID BIGINT NOT NULL AUTO_INCREMENT, ACTIVE BOOLEAN, MANUFACTUREYEAR INTEGER, MODELYEAR INTEGER, PLATE VARCHAR, UPDATEDIN TIMESTAMP, COLOR_ID BIGINT, PRIMARY KEY (ID));
ALTER TABLE vehicle ADD CONSTRAINT FK_vehicle_COLOR_ID FOREIGN KEY (COLOR_ID) REFERENCES color (ID);

